import json
import os
from typing import Dict, List, Set, Optional
from pathlib import Path
import difflib

DATA_DIR = Path(__file__).resolve().parent.parent.parent / "data"
SKILL_DICT_FILE = DATA_DIR / "skill_dict.json"
CANDIDATE_FILE = DATA_DIR / "skill_candidates.json"


FAMOUS_COMPANIES: Set[str] = {
    "google", "alibaba", "tencent", "baidu", "bytedance", "microsoft", "amazon",
    "meta", "apple", "netflix", "tesla", "nvidia", "oracle", "ibm", "salesforce",
    "adobe", "cisco", "intel", "huawei", "xiaomi", "meituan", "jd", "netease",
    "didi", "ant", "蚂蚁", "阿里", "腾讯", "百度", "字节", "华为", "小米",
    "美团", "京东", "网易", "滴滴"
}

EDUCATION_LEVELS: Dict[str, int] = {
    "博士": 5, "phd": 5, "doctorate": 5,
    "硕士": 4, "master": 4, "研究生": 4,
    "本科": 3, "bachelor": 3, "学士": 3,
    "大专": 2, "associate": 2, "专科": 2,
    "高中": 1, "high school": 1,
}

DEFAULT_SKILL_SYNONYMS: Dict[str, List[str]] = {
    "Python": ["python3", "py", "python 2", "python 3", "cpython", "python语言"],
    "Java": ["j2se", "j2ee", "javase", "javaee", "openjdk", "jdk", "java语言"],
    "JavaScript": ["js", "ecmascript", "es6", "es5", "es2015", "es2017", "es2020", "vanilla js"],
    "TypeScript": ["ts", "tsx", "typescript2", "typescript3", "typescript4", "typescript5"],
    "C++": ["cpp", "cplusplus", "c plus plus", "c++11", "c++14", "c++17", "c++20"],
    "C#": ["csharp", "c sharp", ".net", "dotnet", "asp.net", "aspnet", "c#语言"],
    "Go": ["golang", "go lang", "go language", "go语言"],
    "Rust": ["rustlang", "rust lang", "rust语言"],
    "PHP": ["php7", "php8", "php语言"],
    "Ruby": ["ruby语言", "ruby on rails", "rails"],
    "Swift": ["swiftui", "swift ui", "ios swift", "swift语言"],
    "Kotlin": ["kotlin android", "android kotlin", "kotlin语言"],
    "Scala": ["scala语言", "scalajs"],
    "R": ["r语言", "r-lang", "rlang"],
    "Perl": ["perl5", "perl语言"],
    "Lua": ["lua语言", "lua脚本"],
    "Elixir": ["elixir语言", "phoenix"],
    "Haskell": ["haskell语言"],
    "Clojure": ["clojure语言", "clj"],
    "Dart": ["dartlang", "dart language", "dart语言"],
    "Shell": ["shell脚本", "bash", "zsh", "sh"],
    "PowerShell": ["powershell脚本", "ps1"],
    "SQL": ["sql server", "t-sql", "transact sql", "plsql", "pl/sql", "ansi sql", "结构化查询语言"],
    "HTML": ["html5", "html 5", "xhtml", "超文本标记语言"],
    "CSS": ["css3", "css 3", "层叠样式表"],
    "SCSS": ["scss预处理", "sass", "scss样式"],
    "Less": ["less css", "less预处理", "less样式"],
    "Sass": ["sass预处理", "sass样式"],
    "Tailwind CSS": ["tailwind", "tailwindcss", "tailwind样式"],
    "Bootstrap": ["bootstrap5", "bootstrap4", "bootstrap3", "bootstrap框架"],
    "Ant Design": ["antd", "ant design pro", "ant-design"],
    "Element UI": ["element-plus", "elementui", "element-ui"],
    "Material UI": ["mui", "material-ui", "material ui"],
    "React": ["reactjs", "react.js", "react js", "react hooks", "react18", "react19"],
    "React Native": ["rn", "reactnative", "mobile react"],
    "React Router": ["react-router", "react router dom", "react-router-dom"],
    "Redux": ["redux toolkit", "reduxjs", "react redux"],
    "Zustand": ["zustand状态管理"],
    "MobX": ["mobx状态管理", "mobx-react"],
    "Vue.js": ["vue", "vuejs", "vue3", "vue2", "vue.js"],
    "Nuxt.js": ["nuxt", "nuxt3", "nuxt.js"],
    "Vuex": ["vue状态管理", "vuex store"],
    "Pinia": ["pinia状态管理", "vue pinia"],
    "Angular": ["angularjs", "angular.js", "angular2", "angular4", "angular6", "angular8", "angular10", "angular12", "angular14", "angular16"],
    "RxJS": ["rxjs响应式", "reactivex"],
    "NgRx": ["ngrx状态管理"],
    "Svelte": ["sveltejs", "svelte框架"],
    "SolidJS": ["solid js", "solid框架"],
    "Next.js": ["next", "nextjs", "next13", "next14", "next15"],
    "Remix": ["remix框架", "remix run"],
    "Gatsby": ["gatsbyjs", "gatsby框架"],
    "Astro": ["astro框架", "astrojs"],
    "Nuxt": ["nuxt框架", "nuxtjs"],
    "Node.js": ["node", "nodejs", "node js"],
    "Express": ["expressjs", "express框架", "express.js"],
    "Koa": ["koajs", "koa框架", "koa.js"],
    "NestJS": ["nestjs", "nest.js", "nest框架"],
    "Fastify": ["fastify框架", "fastify.js"],
    "Hapi": ["hapijs", "hapi框架"],
    "Django": ["django框架", "django rest", "django-rest-framework", "drf"],
    "Flask": ["flask框架", "flask restful", "flask-restful"],
    "FastAPI": ["fast api", "fastapi框架"],
    "Tornado": ["tornado框架"],
    "Sanic": ["sanic框架"],
    "Pyramid": ["pyramid框架"],
    "Celery": ["celery任务队列", "celery分布式"],
    "SQLAlchemy": ["sqlalchemy orm", "sa"],
    "Alembic": ["alembic迁移"],
    "Spring": ["spring framework", "spring core", "spring aop", "spring ioc", "spring框架"],
    "Spring Boot": ["springboot", "spring boot 2", "spring boot 3", "spring mvc", "springmvc"],
    "Spring Cloud": ["spring cloud", "springcloud"],
    "Spring Security": ["spring security", "springsecurity"],
    "MyBatis": ["mybatis", "ibatis"],
    "Hibernate": ["hibernate orm", "jpa", "hibernate框架"],
    "Gradle": ["gradle构建", "gradle build"],
    "Maven": ["maven构建", "maven build", "pom"],
    "Quarkus": ["quarkus框架"],
    "Vert.x": ["vertx", "vert.x框架"],
    "Laravel": ["laravel框架", "laravel php"],
    "Symfony": ["symfony框架", "symfony php"],
    "CodeIgniter": ["codeigniter框架", "ci框架"],
    "Gin": ["gin框架", "gin go"],
    "Echo": ["echo框架", "echo go"],
    "Fiber": ["fiber框架", "fiber go"],
    "Beego": ["beego框架", "beego go"],
    "Actix": ["actix-web", "actix框架"],
    "Rocket": ["rocket框架", "rocket rust"],
    "Rails": ["ruby on rails", "rails框架", "ror"],
    "Sinatra": ["sinatra框架"],
    "MySQL": ["mysql5", "mysql8", "mariadb", "mysql server", "mysql数据库"],
    "PostgreSQL": ["postgres", "postgresql12", "postgresql14", "postgresql16", "pg", "pg数据库"],
    "MongoDB": ["mongo", "nosql mongo", "mongodb数据库"],
    "Redis": ["redis cluster", "redis sentinel", "redis cache", "redis缓存"],
    "SQLite": ["sqlite3", "sqlite数据库"],
    "Oracle DB": ["oracle数据库", "oracle db", "oracle rdbms"],
    "SQL Server": ["mssql", "microsoft sql server", "sqlserver"],
    "Cassandra": ["apache cassandra", "cassandra数据库"],
    "CockroachDB": ["cockroach db", "crdb"],
    "TiDB": ["tidb数据库", "pingcap"],
    "ClickHouse": ["clickhouse数据库", "ch数据库"],
    "Neo4j": ["neo4j图数据库", "图数据库"],
    "InfluxDB": ["influxdb时序", "时序数据库"],
    "DynamoDB": ["dynamodb aws", "aws dynamo"],
    "Firebase": ["firebase数据库", "firestore"],
    "Supabase": ["supabase数据库", "supabase平台"],
    "CouchDB": ["couchdb数据库", "couch db"],
    "Docker": ["docker-compose", "docker compose", "dockerfile", "containerization", "容器化"],
    "Kubernetes": ["k8s", "kubernets", "k8s编排"],
    "Helm": ["helm chart", "helm k8s"],
    "Istio": ["istio服务网格", "service mesh"],
    "Consul": ["consul服务发现", "consul kv"],
    "etcd": ["etcd分布式", "etcd kv"],
    "Envoy": ["envoy代理", "envoy网关"],
    "Docker Swarm": ["swarm集群", "docker swarm"],
    "Knative": ["knative serverless"],
    "ArgoCD": ["argocd部署", "argo cd"],
    "Tekton": ["tekton ci", "tekton pipeline"],
    "AWS": ["amazon web services", "aws cloud", "aws云"],
    "AWS Lambda": ["lambda", "aws lambda", "lambda函数"],
    "AWS EC2": ["ec2", "aws ec2"],
    "AWS S3": ["s3", "aws s3", "s3存储"],
    "AWS RDS": ["rds", "aws rds"],
    "AWS ECS": ["ecs", "aws ecs", "fargate"],
    "AWS EKS": ["eks", "aws eks"],
    "AWS CloudFormation": ["cloudformation", "cfn"],
    "GCP": ["google cloud", "google cloud platform", "gcp cloud", "谷歌云"],
    "GKE": ["google kubernetes engine", "gke集群"],
    "BigQuery": ["google bigquery", "bigquery数据仓库"],
    "Azure": ["microsoft azure", "azure cloud", "微软云"],
    "Azure AKS": ["aks", "azure kubernetes"],
    "Azure Functions": ["azure函数", "azure serverless"],
    "Alibaba Cloud": ["阿里云", "alicloud", "aliyun"],
    "Tencent Cloud": ["腾讯云", "tencent cloud"],
    "Huawei Cloud": ["华为云", "huawei cloud"],
    "Vercel": ["vercel部署", "vercel平台"],
    "Netlify": ["netlify部署", "netlify平台"],
    "Heroku": ["heroku部署", "heroku平台"],
    "DigitalOcean": ["digitalocean云", "do云"],
    "Terraform": ["terraform iac", "infrastructure as code", "terraform基础设施"],
    "Ansible": ["ansible自动化", "ansible playbook"],
    "Pulumi": ["pulumi iac", "pulumi基础设施"],
    "CloudFormation": ["cloudformation模板"],
    "Packer": ["packer镜像", "packer构建"],
    "Vagrant": ["vagrant虚拟机"],
    "CI/CD": ["cicd", "ci cd", "continuous integration", "continuous deployment", "持续集成", "持续部署"],
    "Jenkins": ["jenkins ci", "jenkins流水线"],
    "GitHub Actions": ["github actions", "gh actions", "github ci"],
    "GitLab CI": ["gitlab ci", "gitlab pipeline"],
    "CircleCI": ["circleci构建"],
    "Travis CI": ["travis ci", "travis构建"],
    "Bamboo": ["bamboo ci", "bamboo构建"],
    "TeamCity": ["teamcity ci"],
    "Git": ["gitflow", "git flow", "github", "gitlab", "bitbucket", "git版本控制"],
    "SVN": ["subversion", "svn版本控制"],
    "Mercurial": ["hg", "mercurial版本控制"],
    "Prometheus": ["prometheus监控", "prometheus指标"],
    "Grafana": ["grafana面板", "grafana可视化"],
    "Datadog": ["datadog监控", "datadog apm"],
    "New Relic": ["newrelic", "new relic监控"],
    "Zabbix": ["zabbix监控"],
    "Nagios": ["nagios监控"],
    "ELK Stack": ["elk", "elasticsearch logstash kibana", "elk日志"],
    "Jaeger": ["jaeger链路追踪", "分布式追踪"],
    "Zipkin": ["zipkin链路追踪"],
    "OpenTelemetry": ["opentelemetry", "otel", "otel可观测"],
    "Fluentd": ["fluentd日志", "fluentd收集"],
    "Logstash": ["logstash日志", "logstash管道"],
    "Nginx": ["nginx server", "nginx反向代理", "nginx网关"],
    "Apache": ["apache httpd", "apache server", "httpd"],
    "HAProxy": ["haproxy负载均衡", "haproxy代理"],
    "Traefik": ["traefik网关", "traefik代理"],
    "Envoy Proxy": ["envoy网关"],
    "Kong": ["kong网关", "kong api gateway"],
    "API Gateway": ["api网关", "网关"],
    "REST API": ["rest", "restful", "rest api", "restful api", "http api"],
    "GraphQL": ["graph ql", "gql"],
    "gRPC": ["grpc", "google rpc"],
    "WebSocket": ["ws", "socket.io", "socketio", "realtime", "实时通信"],
    "Microservices": ["microservice", "micro service", "micro services", "soa", "微服务"],
    "Event-Driven": ["event driven", "事件驱动", "eda"],
    "CQRS": ["cqrs模式", "命令查询分离"],
    "Event Sourcing": ["event sourcing", "事件溯源"],
    "DDD": ["domain driven design", "领域驱动设计"],
    "SOLID": ["solid原则", "solid设计"],
    "Design Patterns": ["设计模式", "design pattern", "gof"],
    "Clean Architecture": ["整洁架构", "clean arch"],
    "Hexagonal Architecture": ["六边形架构", "ports and adapters"],
    "Kafka": ["apache kafka", "kafka streams", "kafka消息队列"],
    "RabbitMQ": ["rabbit mq", "amqp", "rabbitmq消息队列"],
    "ActiveMQ": ["activemq消息队列"],
    "Pulsar": ["apache pulsar", "pulsar消息"],
    "NATS": ["nats消息", "nats io"],
    "ZeroMQ": ["zeromq", "zmq"],
    "RocketMQ": ["rocketmq消息", "apache rocketmq"],
    "Machine Learning": ["ml", "machinelearning", "statistical learning", "机器学习"],
    "Deep Learning": ["dl", "deeplearning", "neural networks", "nn", "深度学习"],
    "PyTorch": ["pytorch2", "torch", "pytorch lightning", "lightning"],
    "TensorFlow": ["tf", "tensorflow2", "keras", "tf2"],
    "Keras": ["keras框架", "keras神经网络"],
    "Scikit-learn": ["sklearn", "scikit learn", "scikitlearn"],
    "XGBoost": ["xgboost算法", "xgb"],
    "LightGBM": ["lightgbm算法", "lgbm"],
    "CatBoost": ["catboost算法"],
    "Hugging Face": ["huggingface", "transformers库", "hf"],
    "Transformers": ["transformer模型", "transformers库", "huggingface transformers"],
    "LangChain": ["langchain框架", "lang chain"],
    "LLM": ["large language model", "大语言模型", "大模型", "gpt", "chatgpt", "claude"],
    "RAG": ["retrieval augmented generation", "检索增强生成"],
    "Fine-tuning": ["微调", "finetune", "fine tune", "模型微调"],
    "Prompt Engineering": ["提示工程", "prompt设计"],
    "Reinforcement Learning": ["rl", "reinforcementlearning", "强化学习"],
    "NLP": ["natural language processing", "nlp processing", "text mining", "自然语言处理"],
    "Computer Vision": ["cv", "computer vision", "image processing", "image recognition", "计算机视觉"],
    "Object Detection": ["目标检测", "object detection", "yolo"],
    "YOLO": ["yolov5", "yolov8", "yolo目标检测"],
    "OCR": ["optical character recognition", "文字识别", "光学字符识别"],
    "Speech Recognition": ["语音识别", "asr", "speech to text"],
    "GAN": ["generative adversarial network", "生成对抗网络"],
    "Diffusion Models": ["扩散模型", "stable diffusion", "diffusion"],
    "Stable Diffusion": ["sd", "stablediffusion", "stable diffusion模型"],
    "MLOps": ["ml ops", "机器学习运维"],
    "MLflow": ["mlflow实验", "mlflow跟踪"],
    "Weights & Biases": ["wandb", "w&b", "weights and biases"],
    "ONNX": ["onnx格式", "onnx runtime"],
    "TensorRT": ["tensorrt推理", "trt"],
    "Data Analysis": ["data analytics", "data analyst", "analytics", "数据分析"],
    "Data Engineering": ["data engineer", "数据工程", "数据工程师"],
    "ETL": ["etl", "extract transform load", "数据抽取"],
    "Data Pipeline": ["数据管道", "data pipeline", "数据流水线"],
    "Data Warehousing": ["数据仓库", "data warehouse", "数仓"],
    "Data Lake": ["数据湖", "data lakehouse"],
    "Apache Spark": ["spark", "pyspark", "spark大数据"],
    "Apache Flink": ["flink", "flink流计算", "apache flink"],
    "Apache Hadoop": ["hadoop", "hdfs", "mapreduce"],
    "Apache Hive": ["hive", "hive sql", "hql"],
    "Apache Airflow": ["airflow", "airflow调度", "airflow dag"],
    "Apache Beam": ["beam", "apache beam", "dataflow"],
    "dbt": ["dbt数据", "dbt转换", "data build tool"],
    "Pandas": ["pandas dataframe", "pd", "pandas数据处理"],
    "NumPy": ["numpy array", "np", "numpy数值计算"],
    "Polars": ["polars dataframe", "polars数据处理"],
    "Dask": ["dask并行", "dask分布式"],
    "Ray": ["ray分布式", "ray并行"],
    "Apache Kafka Streams": ["kafka streams", "kafka流处理"],
    "Snowflake": ["snowflake数据仓库", "snowflake数仓"],
    "Databricks": ["databricks平台", "databricks spark"],
    "Tableau": ["tableau desktop", "tableau server", "tableau可视化"],
    "Power BI": ["powerbi", "ms power bi", "business intelligence", "powerbi报表"],
    "Superset": ["apache superset", "superset可视化"],
    "Metabase": ["metabase可视化", "metabase报表"],
    "Looker": ["looker可视化", "looker报表"],
    "Grafana": ["grafana面板", "grafana仪表盘"],
    "Redash": ["redash可视化"],
    "Selenium": ["selenium webdriver", "webdriver", "selenium测试"],
    "Cypress": ["cypress io", "e2e testing", "cypress测试"],
    "Playwright": ["playwright测试", "playwright e2e"],
    "Puppeteer": ["puppeteer测试", "puppeteer自动化"],
    "Jest": ["jest testing", "jestjs", "jest单元测试"],
    "Mocha": ["mocha js", "mocha testing", "mocha测试"],
    "Vitest": ["vitest测试", "vitest单元测试"],
    "Pytest": ["pytest测试", "pytest python"],
    "unittest": ["python unittest", "unit test"],
    "JUnit": ["junit测试", "junit5", "junit java"],
    "TestNG": ["testng测试", "testng java"],
    "RSpec": ["rspec测试", "rspec ruby"],
    "Go Test": ["go test", "gotest"],
    "Postman": ["postman api", "api testing", "postman接口测试"],
    "JMeter": ["jmeter压测", "jmeter性能测试"],
    "Locust": ["locust压测", "locust性能测试"],
    "k6": ["k6压测", "k6性能测试"],
    "Gatling": ["gatling压测", "gatling性能测试"],
    "LoadRunner": ["loadrunner压测"],
    "Chaos Engineering": ["混沌工程", "chaos eng", "chaos testing"],
    "Litmus": ["litmus混沌"],
    "OWASP": ["owasp安全", "owasp top 10"],
    "Penetration Testing": ["渗透测试", "pentest", "pen testing"],
    "Vulnerability Assessment": ["漏洞评估", "vulnerability scanning"],
    "Security Audit": ["安全审计", "security auditing"],
    "Encryption": ["加密", "cryptography", "密码学"],
    "SSL/TLS": ["ssl", "tls", "https", "证书"],
    "OAuth": ["oauth2", "oauth 2.0", "openid", "openid connect", "sso"],
    "JWT": ["json web token", "jwt token", "jwt认证"],
    "RBAC": ["role based access control", "角色权限", "基于角色的访问控制"],
    "ABAC": ["attribute based access control", "基于属性的访问控制"],
    "WAF": ["web application firewall", "web防火墙"],
    "IDS/IPS": ["入侵检测", "intrusion detection", "intrusion prevention"],
    "SIEM": ["siem安全", "安全信息和事件管理"],
    "SOC": ["安全运营中心", "security operations center"],
    "Compliance": ["合规", "gdpr", "hipaa", "pci dss"],
    "SAST": ["静态应用安全测试", "static analysis"],
    "DAST": ["动态应用安全测试", "dynamic analysis"],
    "SonarQube": ["sonarqube代码质量", "sonar"],
    "Snyk": ["snyk安全扫描"],
    "Trivy": ["trivy容器扫描"],
    "Falco": ["falco运行时安全"],
    "TCP/IP": ["tcp", "ip", "networking", "network protocol", "网络协议"],
    "DNS": ["domain name system", "域名系统"],
    "CDN": ["content delivery network", "内容分发网络"],
    "Load Balancing": ["负载均衡", "load balancer", "lb"],
    "VPN": ["虚拟专用网", "virtual private network"],
    "Firewall": ["防火墙", "firewall规则"],
    "SDN": ["software defined networking", "软件定义网络"],
    "HTTP": ["http协议", "http2", "http3"],
    "HTTPS": ["https协议", "安全http"],
    "FTP": ["文件传输协议", "file transfer protocol"],
    "SSH": ["secure shell", "ssh协议"],
    "gRPC": ["grpc协议", "google rpc"],
    "Thrift": ["thrift rpc", "apache thrift"],
    "Avro": ["apache avro", "avro序列化"],
    "Protobuf": ["protocol buffers", "protobuf序列化", "pb"],
    "Agile": ["scrum", "agile methodology", "sprint", "敏捷开发", "敏捷"],
    "Scrum": ["scrum框架", "scrum master", "scrum敏捷"],
    "Kanban": ["看板", "kanban方法"],
    "Lean": ["精益", "lean方法"],
    "Waterfall": ["瀑布模型", "waterfall model"],
    "SAFe": ["scaled agile framework", "safe框架"],
    "JIRA": ["jira atlassian", "confluence", "jira管理"],
    "Confluence": ["confluence文档", "confluence wiki"],
    "Notion": ["notion文档", "notion协作"],
    "Trello": ["trello看板"],
    "Asana": ["asana项目管理"],
    "Linear": ["linear项目管理"],
    "Figma": ["figma设计", "ui设计", "figma原型"],
    "Sketch": ["sketch设计", "sketch ui"],
    "Adobe XD": ["xd设计", "adobe xd"],
    "InVision": ["invision原型", "invision设计"],
    "Axure": ["axure原型", "axure rp"],
    "Principle": ["principle动效", "principle设计"],
    "Framer": ["framer原型", "framer设计"],
    "Zeplin": ["zeplin标注", "zeplin切图"],
    "User Research": ["用户研究", "user study", "ux research"],
    "UX Design": ["用户体验设计", "ux", "user experience"],
    "UI Design": ["界面设计", "ui", "user interface", "界面设计师"],
    "Interaction Design": ["交互设计", "ixd", "interaction design"],
    "Information Architecture": ["信息架构", "ia"],
    "Wireframing": ["线框图", "wireframe"],
    "Prototyping": ["原型设计", "prototype"],
    "Usability Testing": ["可用性测试", "usability test"],
    "A/B Testing": ["ab测试", "ab test", "ab实验", "分流实验"],
    "Design System": ["设计系统", "design system"],
    "Accessibility": ["无障碍设计", "a11y", "可访问性"],
    "Responsive Design": ["响应式设计", "responsive"],
    "Mobile Design": ["移动端设计", "mobile ui"],
    "Product Management": ["产品管理", "product manager", "pm"],
    "Product Strategy": ["产品策略", "product strategy"],
    "Roadmap": ["路线图", "产品路线图"],
    "User Story": ["用户故事", "user stories"],
    "PRD": ["product requirements document", "产品需求文档"],
    "MRD": ["market requirements document", "市场需求文档"],
    "BRD": ["business requirements document", "商业需求文档"],
    "Competitive Analysis": ["竞品分析", "competitive analysis"],
    "Market Research": ["市场调研", "market research"],
    "Growth Hacking": ["增长黑客", "growth hack"],
    "SEO": ["search engine optimization", "搜索引擎优化"],
    "SEM": ["search engine marketing", "搜索引擎营销"],
    "Content Strategy": ["内容策略", "content strategy"],
    "Social Media Marketing": ["社交媒体营销", "social media"],
    "Email Marketing": ["邮件营销", "email marketing"],
    "CRM": ["customer relationship management", "客户关系管理"],
    "Salesforce CRM": ["salesforce平台"],
    "HubSpot": ["hubspot crm", "hubspot营销"],
    "Data Visualization": ["数据可视化", "dataviz"],
    "Statistical Analysis": ["统计分析", "statistical modeling"],
    "A/B Testing": ["ab测试", "ab实验"],
    "Cohort Analysis": ["队列分析", "cohort"],
    "Funnel Analysis": ["漏斗分析", "funnel"],
    "Retention Analysis": ["留存分析", "retention"],
    "Blockchain": ["block chain", "区块链"],
    "Smart Contract": ["智能合约", "solidity合约"],
    "Solidity": ["solidity语言", "solidity合约"],
    "Web3": ["web3.js", "web 3", "web3开发"],
    "Ethereum": ["以太坊", "eth"],
    "Hyperledger": ["hyperledger fabric", "hyperledger区块链"],
    "DeFi": ["去中心化金融", "decentralized finance"],
    "NFT": ["non-fungible token", "非同质化代币"],
    "IoT": ["internet of things", "物联网"],
    "Embedded Systems": ["嵌入式系统", "embedded"],
    "Arduino": ["arduino开发", "arduino单片机"],
    "Raspberry Pi": ["树莓派", "raspberry pi"],
    "MQTT": ["mqtt协议", "mqtt物联网"],
    "ROS": ["robot operating system", "机器人操作系统"],
    "Edge Computing": ["边缘计算", "edge computing"],
    "Augmented Reality": ["ar", "增强现实"],
    "Virtual Reality": ["vr", "虚拟现实"],
    "Mixed Reality": ["mr", "混合现实"],
    "Unity": ["unity3d", "unity游戏", "unity引擎"],
    "Unreal Engine": ["ue", "ue4", "ue5", "unreal引擎"],
    "Game Development": ["游戏开发", "game dev"],
    "3D Modeling": ["3d建模", "3d model"],
    "Blender": ["blender3d", "blender建模"],
    "AutoCAD": ["autocad设计", "cad"],
    "DevOps": ["dev ops", "sre", "site reliability", "运维开发"],
    "SRE": ["site reliability engineering", "站点可靠性工程"],
    "Platform Engineering": ["平台工程", "platform eng"],
    "Infrastructure": ["基础设施", "infra"],
    "Monitoring": ["监控", "可观测性", "observability"],
    "Incident Management": ["事件管理", "oncall", "on-call"],
    "Disaster Recovery": ["灾难恢复", "dr", "容灾"],
    "High Availability": ["高可用", "ha", "high avail"],
    "Scalability": ["可扩展性", "scalable", "弹性伸缩"],
    "Performance Optimization": ["性能优化", "performance tuning", "调优"],
    "Cost Optimization": ["成本优化", "finops"],
    "Capacity Planning": ["容量规划", "capacity"],
    "Linux": ["unix", "ubuntu", "centos", "debian", "redhat", "rhel", "linux系统"],
    "Windows Server": ["windows服务器", "win server"],
    "macOS": ["mac os", "macos系统"],
    "Android": ["android sdk", "android development", "android studio", "安卓开发"],
    "iOS": ["ios development", "ios sdk", "xcode", "objective-c", "objectivec", "苹果开发"],
    "Flutter": ["flutter dart", "dart flutter", "flutter跨端"],
    "React Native": ["rn", "reactnative", "mobile react", "react native跨端"],
    "Ionic": ["ionic框架", "ionic跨端"],
    "Capacitor": ["capacitor跨端"],
    "Electron": ["electron桌面", "electron js"],
    "Tauri": ["tauri桌面", "tauri应用"],
    "Qt": ["qt框架", "qt开发"],
    "Jupyter": ["jupyter notebook", "jupyterlab", "jupyter"],
    "Colab": ["google colab", "colab笔记本"],
    "Conda": ["conda环境", "miniconda", "anaconda"],
    "pip": ["pip包管理", "pip install"],
    "npm": ["npm包管理", "node package manager"],
    "yarn": ["yarn包管理"],
    "pnpm": ["pnpm包管理"],
    "Poetry": ["poetry python", "poetry依赖"],
    "Bazel": ["bazel构建", "bazel build"],
    "Make": ["makefile", "make构建"],
    "CMake": ["cmake构建", "cmake build"],
    "Webpack": ["webpack4", "webpack5", "module bundler", "webpack打包"],
    "Vite": ["vitejs", "vite.js", "vite构建"],
    "Rollup": ["rollup打包", "rollupjs"],
    "esbuild": ["esbuild打包", "esbuild编译"],
    "SWC": ["swc编译", "swc打包"],
    "Babel": ["babel编译", "babel转译", "babeljs"],
    "PostCSS": ["postcss处理", "postcss插件"],
    "ESLint": ["eslint检查", "eslint代码规范"],
    "Prettier": ["prettier格式化", "prettier代码风格"],
    "Pylint": ["pylint检查", "pylint代码规范"],
    "Black": ["black格式化", "black代码风格"],
    "Ruff": ["ruff检查", "ruff代码规范"],
    "MyPy": ["mypy类型", "mypy检查"],
    "TypeScript ESLint": ["tslint", "typescript eslint"],
    "Stylelint": ["stylelint css", "css检查"],
    "Husky": ["husky钩子", "git hooks"],
    "lint-staged": ["lint staged", "暂存区检查"],
    "Commitlint": ["commit lint", "提交规范"],
    "Storybook": ["storybook组件", "storybook文档"],
    "Chromatic": ["chromatic可视化测试"],
    "Lerna": ["lerna monorepo"],
    "Turborepo": ["turborepo monorepo"],
    "Nx": ["nx monorepo", "nrwl nx"],
    "pnpm workspace": ["pnpm工作区"],
    "Apache": ["apache httpd", "apache server", "httpd服务器"],
    "Caddy": ["caddy服务器", "caddy反向代理"],
    "OpenAPI": ["swagger", "openapi规范", "swagger文档"],
    "Swagger": ["swagger ui", "swagger api"],
    "gRPC-Web": ["grpc web", "grpc前端"],
    "WebAssembly": ["wasm", "web assembly"],
    "WASM": ["wasm运行时"],
    "PWA": ["progressive web app", "渐进式web应用"],
    "Service Worker": ["service worker缓存"],
    "WebRTC": ["webrtc实时通信", "实时音视频"],
    "IndexedDB": ["indexeddb本地存储"],
    "LocalStorage": ["local storage", "本地存储"],
    "SessionStorage": ["session storage"],
    "Cookie": ["cookies", "http cookie"],
    "CORS": ["cross origin resource sharing", "跨域"],
    "CSRF": ["cross site request forgery", "跨站请求伪造"],
    "XSS": ["cross site scripting", "跨站脚本"],
    "SQL Injection": ["sql注入", "sql injection"],
    "Rate Limiting": ["限流", "rate limit", "频率限制"],
    "Circuit Breaker": ["熔断器", "circuit breaker pattern"],
    "Retry": ["重试机制", "retry pattern"],
    "Idempotency": ["幂等性", "idempotent"],
    "Saga Pattern": ["saga模式", "saga分布式事务"],
    "Two-Phase Commit": ["两阶段提交", "2pc", "二阶段提交"],
    "TCC": ["try confirm cancel", "tcc事务"],
    "Sharding": ["分片", "shard", "数据分片"],
    "Partitioning": ["分区", "partition", "数据分区"],
    "Replication": ["复制", "副本", "数据复制"],
    "Caching": ["缓存", "cache strategy", "缓存策略"],
    "CDN": ["content delivery network", "内容分发", "cdn加速"],
    "DNS": ["域名解析", "dns服务"],
    "OAuth 2.0": ["oauth2认证", "oauth2.0"],
    "SAML": ["saml认证", "saml sso"],
    "LDAP": ["ldap认证", "ldap目录"],
    "Kaniko": ["kaniko镜像构建"],
    "Buildkit": ["buildkit构建", "buildkit docker"],
    "Skaffold": ["skaffold k8s开发"],
    "Tilt": ["tilt k8s开发"],
    "Prow": ["prow ci", "prow k8s ci"],
    "Vault": ["hashicorp vault", "vault密钥", "vault秘钥管理"],
    "Sealed Secrets": ["sealed secrets", "加密秘钥"],
    "Cert-Manager": ["cert manager", "证书管理"],
    "ExternalDNS": ["external dns", "外部dns"],
    "Descheduler": ["descheduler调度"],
    "Cluster Autoscaler": ["集群自动扩缩容", "autoscaler"],
    "KEDA": ["keda自动伸缩", "kubernetes event driven autoscaling"],
    "Velero": ["velero备份", "k8s备份"],
    "Thanos": ["thanos监控", "thanos prometheus"],
    "Loki": ["loki日志", "grafana loki"],
    "Tempo": ["tempo追踪", "grafana tempo"],
    "Pyroscope": ["pyroscope性能", "grafana pyroscope"],
    "OpenSearch": ["opensearch搜索", "opensearch es"],
    "Meilisearch": ["meilisearch搜索", "meili搜索"],
    "Typesense": ["typesense搜索"],
    "Algolia": ["algolia搜索", "algolia api"],
    "Strapi": ["strapi cms", "strapi内容管理"],
    "Contentful": ["contentful cms", "contentful内容管理"],
    "Wordpress": ["wordpress cms", "wp"],
    "Sanity": ["sanity cms", "sanity内容管理"],
    "Prisma": ["prisma orm", "prisma数据库"],
    "TypeORM": ["typeorm orm", "typeorm数据库"],
    "Sequelize": ["sequelize orm", "sequelize数据库"],
    "Mongoose": ["mongoose orm", "mongoose mongodb"],
    "Knex": ["knex查询", "knex sql"],
    "Objection.js": ["objection orm", "objectionjs"],
    "Drizzle": ["drizzle orm", "drizzle数据库"],
    "Playwright": ["playwright自动化", "playwright测试"],
    "Appium": ["appium移动测试", "appium自动化"],
    "Detox": ["detox测试", "detox移动测试"],
    "Espresso": ["espresso android测试"],
    "XCTest": ["xctest ios测试"],
    "Calabash": ["calabash移动测试"],
    "Robot Framework": ["robot framework测试", "robot自动化"],
    "Cucumber": ["cucumber bdd", "cucumber测试"],
    "SpecFlow": ["specflow bdd"],
    "TestCafe": ["testcafe测试", "testcafe e2e"],
    "Nightwatch": ["nightwatch测试", "nightwatch e2e"],
    "CodeceptJS": ["codeceptjs测试"],
    "Pact": ["pact契约测试", "contract testing"],
    "Stryker": ["stryker变异测试", "mutation testing"],
    "k6": ["k6负载测试", "k6性能"],
    "Artillery": ["artillery压测", "artillery负载"],
    "Vegeta": ["vegeta压测"],
    "Wrk": ["wrk压测", "wrk基准"],
    "Ab": ["apache bench", "ab压测"],
    "Siege": ["siege压测"],
    "Terraform Cloud": ["terraform cloud管理"],
    "Spacelift": ["spacelift terraform"],
    "Atlantis": ["atlantis terraform"],
    "Crossplane": ["crossplane k8s", "crossplane云资源"],
    "Dapr": ["dapr微服务", "dapr runtime"],
    "OpenFaaS": ["openfaas serverless", "openfaas函数"],
    "Kubeless": ["kubeless serverless"],
    "OpenStack": ["openstack云", "openstack私有云"],
    "Proxmox": ["proxmox虚拟化"],
    "VMware": ["vmware虚拟化", "esxi", "vcenter"],
    "Xen": ["xen虚拟化"],
    "KVM": ["kvm虚拟化"],
    "LXC": ["lxc容器", "lxd"],
    "containerd": ["containerd运行时"],
    "CRI-O": ["cri-o运行时"],
    "Podman": ["podman容器"],
    "Buildah": ["buildah镜像"],
    "Kaniko": ["kaniko构建镜像"],
}


class SkillDictionary:
    def __init__(self):
        self._canonical_to_synonyms: Dict[str, List[str]] = {}
        self._synonym_to_canonical: Dict[str, str] = {}
        self._candidates: List[Dict] = []
        self._load()

    def _load(self):
        DATA_DIR.mkdir(exist_ok=True)
        self._canonical_to_synonyms = dict(DEFAULT_SKILL_SYNONYMS)
        if SKILL_DICT_FILE.exists():
            with open(SKILL_DICT_FILE, "r", encoding="utf-8") as f:
                extra = json.load(f)
                for k, v in extra.items():
                    self._canonical_to_synonyms[k] = self._canonical_to_synonyms.get(k, []) + v
        self._rebuild_index()
        self._load_candidates()

    def _rebuild_index(self):
        self._synonym_to_canonical = {}
        for canonical, syns in self._canonical_to_synonyms.items():
            self._synonym_to_canonical[canonical.lower()] = canonical
            for s in syns:
                self._synonym_to_canonical[s.lower()] = canonical

    def _load_candidates(self):
        if CANDIDATE_FILE.exists():
            with open(CANDIDATE_FILE, "r", encoding="utf-8") as f:
                self._candidates = json.load(f)
        else:
            self._candidates = []

    def _save_candidates(self):
        with open(CANDIDATE_FILE, "w", encoding="utf-8") as f:
            json.dump(self._candidates, f, ensure_ascii=False, indent=2)

    def _save_skills(self):
        to_save = {k: v for k, v in self._canonical_to_synonyms.items()
                   if k not in DEFAULT_SKILL_SYNONYMS or v != DEFAULT_SKILL_SYNONYMS[k]}
        with open(SKILL_DICT_FILE, "w", encoding="utf-8") as f:
            json.dump(to_save, f, ensure_ascii=False, indent=2)

    def all_canonical(self) -> List[str]:
        return list(self._canonical_to_synonyms.keys())

    def normalize(self, term: str) -> Optional[str]:
        if not term:
            return None
        t = term.strip().lower()
        if t in self._synonym_to_canonical:
            return self._synonym_to_canonical[t]
        matches = difflib.get_close_matches(t, list(self._synonym_to_canonical.keys()), n=1, cutoff=0.85)
        if matches:
            return self._synonym_to_canonical[matches[0]]
        return None

    def record_candidate(self, term: str, resume_id: Optional[int] = None):
        t = term.strip().lower()
        if not t or len(t) < 2 or self.normalize(t):
            return
        for c in self._candidates:
            if c["term"].lower() == t:
                c["frequency"] = c.get("frequency", 1) + 1
                self._save_candidates()
                return
        self._candidates.append({
            "term": term.strip(),
            "source_resume_id": resume_id,
            "frequency": 1,
            "first_seen": str(__import__("datetime").datetime.now()),
        })
        self._save_candidates()

    def list_candidates(self) -> List[Dict]:
        return sorted(self._candidates, key=lambda c: -c.get("frequency", 0))

    def approve_candidate(self, term: str, canonical: Optional[str] = None):
        t = term.strip()
        canon = canonical or t
        self._candidates = [c for c in self._candidates if c["term"].strip().lower() != t.lower()]
        self._save_candidates()
        if canon not in self._canonical_to_synonyms:
            self._canonical_to_synonyms[canon] = []
        if t != canon and t.lower() not in [s.lower() for s in self._canonical_to_synonyms[canon]]:
            self._canonical_to_synonyms[canon].append(t)
        self._save_skills()
        self._rebuild_index()

    def add_skill(self, canonical: str, synonyms: Optional[List[str]] = None):
        if canonical not in self._canonical_to_synonyms:
            self._canonical_to_synonyms[canonical] = []
        if synonyms:
            for s in synonyms:
                if s.lower() not in [x.lower() for x in self._canonical_to_synonyms[canonical]]:
                    self._canonical_to_synonyms[canonical].append(s)
        self._save_skills()
        self._rebuild_index()


skill_dict = SkillDictionary()
